- name: Host Prerequisites
  hosts: kafka_broker
  tasks:
    - import_role:
        name: confluent.common
- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: no
  tags:
    - kafka_broker
  tasks:
    - import_role:
        name: confluent.kafka_broker