all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: "/your-ssh-key.pem"
kafka_broker:
  hosts:
    ec2-54-164-53-234.compute-1.amazonaws.com:
    ec2-54-147-107-206.compute-1.amazonaws.com:
    ec2-34-200-216-113.compute-1.amazonaws.com:
zookeeper:
  hosts:
    ec2-54-89-101-78.compute-1.amazonaws.com:
    ec2-3-91-3-248.compute-1.amazonaws.com:
    ec2-34-230-2-120.compute-1.amazonaws.com:
#schema_registry:
#  hosts:
#    ip-172-31-34-246.us-east-2.compute.internal:
#kafka_connect:
#  hosts:
#    ip-172-31-34-246.us-east-2.compute.internal:
#kafka_rest:
#  hosts:
#    ip-172-31-34-246.us-east-2.compute.internal:
#ksql:
#  hosts:
#    ip-172-31-37-15.us-east-2.compute.internal:
#control_center:
#  hosts:
#    ip-172-31-37-15.us-east-2.compute.internal:
