- name: Host Prerequisites
  hosts: zookeeper
  tasks:
    - import_role:
        name: confluent.common
- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: no
  tags:
    - zookeeper
  tasks:
    - import_role:
        name: confluent.zookeeper
